const weatherConditions = {
  sunny: ["Sunny", "Mainly Sunny"],
  suncloud: ["Partly Cloudy", "Mostly Cloudy"],
  cloudy: [
    "Haze",
    "Fog",
    "Ice Fog",
    "Fog Patches",
    "Shallow Fog",
    "Mist",
    "Cloudy",
  ],
  rain: [
    "Light Rain Shower",
    "Light Rain Shower and Flurries",
    "Thunderstorm with Rain",
    "Thunderstorm",
    "Heavy Thunderstorm with Rain",
    "Heavy Thunderstorm",
    "Light Drizzle",
    "Heavy Drizzle",
    "Drizzle",
    "Light Rain and Drizzle",
    "Light Rain",
    "Rain and Drizzle",
    "Rain Shower",
    "Heavy Rain and Drizzle",
    "Heavy Rain Shower",
    "Heavy Rain",
    "Rain",
    "Light Freezing Drizzle",
    "Light Freezing Rain",
    "Heavy Freezing Drizzle",
    "Heavy Freezing Rain",
    "Light Rain and Snow",
    "Heavy Rain Shower and Flurries",
    "Thunderstorm with Heavy Rain",
    "Thunderstorm with Light Rain",
    "Freezing Drizzle",
    "Freezing Rain",
  ],
  snow: [
    "Heavy Rain and Snow",
    "Light Snow",
    "Snow",
    "Flurries",
    "Heavy Flurries",
    "Heavy Snow",
    "Rain and Flurries",
    "Rain and Snow",
    "Light Flurries",
  ],
  clear: [
    "Clear",
    "Mainly Clear",
  ],
};

module.exports = weatherConditions;
