const weatherConditions = {
  sunny: ["sunny", "mainly sunny"],
  suncloud: [
    "partly cloudy",
    "mostly cloudy",
    "a mix of sun and cloud",
    "a few clouds",
  ],
  cloudy: [
    "haze",
    "fog",
    "ice fog",
    "fog patches",
    "shallow fog",
    "mist",
    "cloudy",
    "mostly cloudy",
    "cloudy periods",
    "mainly cloudy",
  ],
  rain: [
    "light rain shower",
    "light rain shower and flurries",
    "thunderstorm with rain",
    "thunderstorm",
    "heavy thunderstorm with rain",
    "heavy thunderstorm",
    "light drizzle",
    "heavy drizzle",
    "drizzle",
    "light rain and drizzle",
    "light rain",
    "rain and drizzle",
    "rain shower",
    "heavy rain and drizzle",
    "heavy rain shower",
    "heavy rain",
    "rain",
    "light freezing drizzle",
    "light freezing rain",
    "heavy freezing drizzle",
    "heavy freezing rain",
    "light rain and snow",
    "heavy rain shower and flurries",
    "thunderstorm with heavy rain",
    "thunderstorm with light rain",
    "freezing drizzle",
    "freezing rain",
    "showers",
    "a few showers",
    "chance of showers",
  ],
  snow: [
    "heavy rain and snow",
    "light snow",
    "snow",
    "flurries",
    "heavy flurries",
    "heavy snow",
    "rain and flurries",
    "rain and snow",
    "light flurries",
    "chance of flurries",
    "periods of snow",
  ],
  clear: ["clear", "mainly clear"],
};

module.exports = weatherConditions;
